import inter from './UI/fonts'; 

export const metadata = {
  title: 'Jhonatan - Portafolio Personal',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
